Testing pipelines

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -4,4 +4,9 @@ set -e
 
 REPO_ROOT="$(dirname $(dirname $(realpath ${BASH_SOURCE[0]:-${(%):-%x}})))"
 
-PACKER_LOG=1 packer build --on-error=cleanup "$REPO_ROOT/packer/$PACKER_TEMPLATE.pkr.hcl"
+echo "$PACKER_TEMPLATE"
+echo "$PACKER_VARIABLES"
+
+exit 1
+
+# PACKER_LOG=1 packer build --on-error=cleanup "$REPO_ROOT/packer/$PACKER_TEMPLATE.pkr.hcl"
