Support building Ubuntu Noble images in CI (#342)
Co-authored-by: wtripp180901 <will.tripp@btinternet.com>
Co-authored-by: Alex Manning <alexm@stackhpc.com>
Co-authored-by: mkjpryor <642657+mkjpryor@users.noreply.github.com>

diff --git a/.github/workflows/build_test_images.yaml b/.github/workflows/build_test_images.yaml
--- a/.github/workflows/build_test_images.yaml
+++ b/.github/workflows/build_test_images.yaml
@@ -1,6 +1,6 @@
 ---
 # yamllint disable rule:line-length
-name: Build, publish and test images
+name: Build, publish and test Ubuntu images
 
 on:  # yamllint disable-line rule:truthy
   workflow_call:
@@ -20,7 +20,6 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       builds: ${{ steps.builds-as-json.outputs.builds }}
-      has_ubuntu_builds: ${{ steps.builds-as-json.outputs.has_ubuntu_builds }}
     permissions:
       contents: read
     steps:
@@ -39,7 +38,6 @@ jobs:
   ensure_source_image:
     needs:
       - read_builds
-    if: needs.read_builds.outputs.has_ubuntu_builds == 'true'
     runs-on: ubuntu-latest
     outputs:
       source_image: ${{ steps.download_source.outputs.source_image_name }}
@@ -84,6 +82,7 @@ jobs:
       packages: write
       id-token: write  # required to get an OIDC token for signing
       security-events: write  # required to upload SARIF files
+      checks: write # to write check-runs statuses
     steps:
       - name: Check out the repository
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -147,13 +146,39 @@ jobs:
           output-file: "${{ steps.build-image.outputs.image-name }}-sbom.json"
           format: syft-json
 
-      - name: Fail if scan has CRITICAL vulnerabilities
+      - name: Scan sbom with Grype
         uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
+        id: scan
         with:
           sbom: "${{ steps.build-image.outputs.image-name }}-sbom.json"
-          output-format: table
-          severity-cutoff: critical
+          severity-cutoff: low
           only-fixed: true
+          output-format: sarif
+          fail-build: false
+
+      - name: Analyse scan and fail workflow if fixed CRITICAL vulnerabilities are not ignored
+        run: |
+          pip install git+https://github.com/stackhpc/grype-analyse@main
+          GRYPE=$(find /tmp -name grype -type f 2>/dev/null | head -1)
+          if [ -z "$GRYPE" ]; then
+            echo "grype binary not found in /tmp"
+            exit 1
+          fi
+          $GRYPE \
+            -c "${GRYPE_CONFIG_FILE}" \
+            --only-fixed \
+            "sbom:${SBOM}" \
+            -o json \
+            --file "${GRYPE_OUTPUT_FILE}"
+          grype-analyse \
+            --config "${GRYPE_CONFIG_FILE}" \
+            --github-checks "${GRYPE_OUTPUT_FILE}"
+        env:
+          SBOM: ${{ steps.build-image.outputs.image-name }}-sbom.json
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GRYPE_ANALYSE_MATRIX: ${{ steps.build-image.outputs.image-name }}
+          GRYPE_OUTPUT_FILE: ${{ steps.build-image.outputs.image-name }}.grype.json
+          GRYPE_CONFIG_FILE: grype-config/${{ matrix.name }}.yaml
 
       - name: Publish image
         id: publish-image
@@ -197,9 +222,7 @@ jobs:
 
   delete_source_image:
     runs-on: ubuntu-latest
-    if: always() && needs.read_builds.outputs.has_ubuntu_builds == 'true'
     needs:
-      - read_builds
       - build_images
       - ensure_source_image
     permissions:
